server:
  port: ${PORT:5000}

eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_PEER_URL}/eureka/
    tls:
      key-password: ${EUREKA_USER_PASSWORD:password}
  server:
    enable-self-preservation: false
    renewalPercentThreshold: 0.33
spring:
  security:
    user:
      password: ${eureka.password}
  config:
    activate:
      on-profile: peer